arrowParens: avoid
useTabs: true
tabWidth: 2
singleQuote: true
semi: false
printWidth: 100
trailingComma: all
plugins: [prettier-plugin-svelte]
overrides:
  - files:
      - '*.md'
      - '*.json'
      - '*.yaml'
      - '*.yml'
    options:
      useTabs: false
      tabWidth: 2
  - files:
      - '*.svelte'
    options:
      parse: svelte
svelteSortOrder: options-scripts-markup-styles
svelteBracketNewLine: true
